spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myappdb?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    cache: false
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 1
        max-wait: -1
    
      
          
server:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  type-aliases-package: com.whl.myapp.model
  mapper-locations: classpath:mapper/*Dao.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: pageNum=page;pageSize=rows;